[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ie_titanic_utils"
authors = [{name = "Felipe Restrepo Cordoba", email = "felipe.restrepo@student.ie.edu"}]
readme = "README.md"
dynamic = ["version", "description"]
